# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arrow.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'arrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rrow.proto\x12\x05\x41rrow\"\x1c\n\x0c\x41rrowRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"5\n\nArrowReply\x12\x13\n\x0b\x61rray_names\x18\x01 \x03(\t\x12\x12\n\narray_sums\x18\x02 \x03(\x01\x32\x42\n\x0c\x41rrowService\x12\x32\n\x08SayArrow\x12\x13.Arrow.ArrowRequest\x1a\x11.Arrow.ArrowReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARROWREQUEST']._serialized_start=22
  _globals['_ARROWREQUEST']._serialized_end=50
  _globals['_ARROWREPLY']._serialized_start=52
  _globals['_ARROWREPLY']._serialized_end=105
  _globals['_ARROWSERVICE']._serialized_start=107
  _globals['_ARROWSERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
